[uwsgi]
module=app:app
logto = /var/log/buaibot.log

master = true
processes = 5
buffer-size = 8192

home = /var/www/BUAIBOT/venv

socket = buaibot.sock
chmod-socket = 666
vacuum = true

callable = run

die-on-term = true